### ISSUE TITLE
ansible-galaxy 2.5.4 - cant find the role

### ISSUE THREAD

**Issue by fuzzyami** [weareinteractive/ansible-docker-compose#5]
yo. thanks for this useful code! unfortunately, I can no longer install it. the following command - `ansible-galaxy install weareinteractive.docker-compose` -  copied from [ansible galaxy](https://galaxy.ansible.com/weareinteractive/docker-compose) , does not work:

`ansible-galaxy install weareinteractive.docker-compose`
```
- downloading role 'docker-compose', owned by weareinteractive
 [WARNING]: - weareinteractive.docker-compose was NOT installed successfully: - sorry, weareinteractive.docker-compose was not
found on https://galaxy.ansible.com.

```

**Comment by franklinkim** [comment]
Hi, just figured out that galaxy seemed to have switch "-" to "_" meaning it's

```bash
ansible-galaxy install weareinteractive.docker_compose
``` 
and not 
```bash
ansible-galaxy install weareinteractive.docker-compose
```
